// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvP62UpV29iG9tL00-gcnZw1lFhAixxwE',
    appId: '1:455037082371:web:085df303f9b4af84536736',
    messagingSenderId: '455037082371',
    projectId: 'yaounde-3658f',
    authDomain: 'yaounde-3658f.firebaseapp.com',
    storageBucket: 'yaounde-3658f.firebasestorage.app',
    measurementId: 'G-BGW9P3YBN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTEE97t2t4LbgzjqF3G0GvvfiaPRztdZc',
    appId: '1:455037082371:android:d8a1d0b4854ac526536736',
    messagingSenderId: '455037082371',
    projectId: 'yaounde-3658f',
    storageBucket: 'yaounde-3658f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvP62UpV29iG9tL00-gcnZw1lFhAixxwE',
    appId: '1:455037082371:web:776e3cc4785b4217536736',
    messagingSenderId: '455037082371',
    projectId: 'yaounde-3658f',
    authDomain: 'yaounde-3658f.firebaseapp.com',
    storageBucket: 'yaounde-3658f.firebasestorage.app',
    measurementId: 'G-YE08CQZ02Y',
  );
}
